# Generated by Django 5.0.4 on 2026-03-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epsilon', models.FloatField(default=1.0)),
                ('delta', models.FloatField(default=1e-05)),
                ('total_budget', models.FloatField(default=10.0)),
                ('consumed_budget', models.FloatField(default=0.0)),
                ('query_count', models.IntegerField(default=0)),
                ('last_query_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_budgets', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Privacy Budget',
                'verbose_name_plural': 'Privacy Budgets',
                'ordering': ['-updated_at'],
            },
        ),
    ]
